// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh5DBtxXkaLpJsNjT6KZfsvfFNGDzSFVs',
    appId: '1:174361140258:web:1c9b187a992edac0c5be7b',
    messagingSenderId: '174361140258',
    projectId: 'fir-wscube-d135a',
    authDomain: 'fir-wscube-d135a.firebaseapp.com',
    storageBucket: 'fir-wscube-d135a.appspot.com',
    measurementId: 'G-97CEJ8KJXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmHPY-y7r6n0PtSqtifpoHGtT3m4QUsqo',
    appId: '1:174361140258:android:2a8dfa7812da5eb9c5be7b',
    messagingSenderId: '174361140258',
    projectId: 'fir-wscube-d135a',
    storageBucket: 'fir-wscube-d135a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmzTc2LgsVF96sSKQsPbfMobEhSWPuTeQ',
    appId: '1:174361140258:ios:b9852fe1f57e374bc5be7b',
    messagingSenderId: '174361140258',
    projectId: 'fir-wscube-d135a',
    storageBucket: 'fir-wscube-d135a.appspot.com',
    iosBundleId: 'com.example.firestoreImageUpWscube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmzTc2LgsVF96sSKQsPbfMobEhSWPuTeQ',
    appId: '1:174361140258:ios:b9852fe1f57e374bc5be7b',
    messagingSenderId: '174361140258',
    projectId: 'fir-wscube-d135a',
    storageBucket: 'fir-wscube-d135a.appspot.com',
    iosBundleId: 'com.example.firestoreImageUpWscube',
  );
}
